// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    ROUTES: string
}

interface WWWAuthenticate {
    realm: string,
    service: string,
}