name = "docker-proxy-worker"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[observability]
enabled = true
head_sampling_rate = 1
